from src.demo.models.grammar import GrammarObject, Terminal
from src.demo.models.tn_rule import RuleGraph, NodeLegacy, NodeTypeLegacy

GRAMMAR = GrammarObject(
    axiom="Program",
    non_terminals=[
        "Program",
        "SubroutineBlock",
        "FuncBlock",
        "ProcBlock",
        "IterBlock",
        "AlgorithmBlock",
        "ExperimentBlock",
        "ParamDecl",
        "TypeDecl",
        "PrimitiveType",
        "StatementList",
        "Statement",
        "Assignment",
        "IfStatement",
        "WhileStatement",
        "ForStatement",
        "ForInStatement",
        "CallStatement",
        "ReturnStatement",
        "YieldStatement",
        "ExitStatement",
        "Condition",
        "LogicalTerm",
        "LogicalFactor",
        "Comparison",
        "Expression",
        "Term",
        "Factor",
        "CallExpr",
        "CollectionLiteral",
        "ArgumentList",
        "ExpCommandList",
        "ExpCommand",
        "ParamCmd",
        "TrialsCmd",
        "SeedCmd",
        "GenCmd",
        "CounterCmd",
        "StopIfCmd",
        "RunCmd",
        "ExportCmd",
    ],
    keys=[
        ("ident", "ALGORITHM"),
        ("ident", "EXPERIMENT"),
        ("ident", "END"),
        ("ident", "IF"),
        ("ident", "THEN"),
        ("ident", "ELSE"),
        ("ident", "ENDIF"),
        ("ident", "WHILE"),
        ("ident", "DO"),
        ("ident", "ENDWHILE"),
        ("ident", "FOR"),
        ("ident", "FROM"),
        ("ident", "TO"),
        ("ident", "ENDFOR"),
        ("ident", "IN"),
        ("ident", "RETURN"),
        ("ident", "YIELD"),
        ("ident", "EXIT"),
        ("ident", "FUNC"),
        ("ident", "PROC"),
        ("ident", "ITER"),
        ("ident", "PARAM"),
        ("ident", "RANGE"),
        ("ident", "TRIALS"),
        ("ident", "SEED"),
        ("ident", "GENERATOR"),
        ("ident", "COUNTER"),
        ("ident", "ON"),
        ("ident", "STOP_IF"),
        ("ident", "RUN"),
        ("ident", "EXPORT"),
        ("ident", "ANY"),
        ("ident", "int"),
        ("ident", "bool"),
        ("ident", "string"),
        ("ident", "float"),
        ("ident", "array"),
        ("ident", "list"),
        ("ident", "of"),
        ("ident", "TRUE"),
        ("ident", "FALSE"),
        ("ident", "AND"),
        ("ident", "OR"),
        ("ident", "NOT"),
        ("ident", "DIV"),
        ("ident", "MOD"),
        ("unknown", "="),
        ("unknown", "+"),
        ("unknown", "-"),
        ("unknown", "*"),
        ("unknown", "/"),
        ("unknown", "<"),
        ("unknown", ">"),
        ("unknown", "<="),
        ("unknown", ">="),
        ("unknown", "=="),
        ("unknown", "!="),
        ("unknown", "("),
        ("unknown", ")"),
        ("unknown", "["),
        ("unknown", "]"),
        ("unknown", "{"),
        ("unknown", "}"),
        ("unknown", ","),
        ("unknown", ":"),
        ("unknown", ".."),
        ("unknown", "."),
    ],
    terminals={
        "ident": Terminal(name="ident", pattern=r"[A-Za-z_][A-Za-z0-9_]*"),
        "number": Terminal(name="number", pattern=r"\d+(\.\d+)?"),
        "string": Terminal(name="string", pattern=r'"[^"]*"'),
        "whitespace": Terminal(name="whitespace", pattern=r"\s+"),
    },
    graphs_rule=[
        RuleGraph(
            name="Program",
            nodes={
                "start": NodeLegacy(
                    type=NodeTypeLegacy.START,
                    str_="Program",
                    nonterminal=None,
                    terminal=None,
                    nextNodes=[],
                ),
                "end": NodeLegacy(
                    type=NodeTypeLegacy.END,
                    str_="",
                    nonterminal=None,
                    terminal=None,
                    nextNodes=[],
                ),
                "n_1": NodeLegacy(
                    type=NodeTypeLegacy.NONTERMINAL,
                    str_="SubroutineBlock",
                    nonterminal="SubroutineBlock",
                    terminal=None,
                    nextNodes=[],
                ),
                "n_2": NodeLegacy(
                    type=NodeTypeLegacy.NONTERMINAL,
                    str_="AlgorithmBlock",
                    nonterminal="AlgorithmBlock",
                    terminal=None,
                    nextNodes=[],
                ),
                "n_3": NodeLegacy(
                    type=NodeTypeLegacy.NONTERMINAL,
                    str_="ExperimentBlock",
                    nonterminal="ExperimentBlock",
                    terminal=None,
                    nextNodes=[],
                ),
            },
            edges=[
                ("n_1", "n_1", ""),
                ("n_1", "n_2", ""),
                ("n_2", "n_3", ""),
                ("start", "n_1", ""),
                ("start", "n_2", ""),
                ("n_3", "end", ""),
            ],
        ),
        RuleGraph(
            name="SubroutineBlock",
            nodes={
                "start": NodeLegacy(
                    type=NodeTypeLegacy.START,
                    str_="SubroutineBlock",
                    nonterminal=None,
                    terminal=None,
                    nextNodes=[],
                ),
                "end": NodeLegacy(
                    type=NodeTypeLegacy.END,
                    str_="",
                    nonterminal=None,
                    terminal=None,
                    nextNodes=[],
                ),
                "n_1": NodeLegacy(
                    type=NodeTypeLegacy.NONTERMINAL,
                    str_="FuncBlock",
                    nonterminal="FuncBlock",
                    terminal=None,
                    nextNodes=[],
                ),
                "n_2": NodeLegacy(
                    type=NodeTypeLegacy.NONTERMINAL,
                    str_="ProcBlock",
                    nonterminal="ProcBlock",
                    terminal=None,
                    nextNodes=[],
                ),
                "n_3": NodeLegacy(
                    type=NodeTypeLegacy.NONTERMINAL,
                    str_="IterBlock",
                    nonterminal="IterBlock",
                    terminal=None,
                    nextNodes=[],
                ),
            },
            edges=[
                ("start", "n_3", ""),
                ("start", "n_1", ""),
                ("start", "n_2", ""),
                ("n_3", "end", ""),
                ("n_1", "end", ""),
                ("n_2", "end", ""),
            ],
        ),
        RuleGraph(
            name="FuncBlock",
            nodes={
                "start": NodeLegacy(
                    type=NodeTypeLegacy.START,
                    str_="FuncBlock",
                    nonterminal=None,
                    terminal=None,
                    nextNodes=[],
                ),
                "end": NodeLegacy(
                    type=NodeTypeLegacy.END,
                    str_="",
                    nonterminal=None,
                    terminal=None,
                    nextNodes=[],
                ),
                "n_1": NodeLegacy(
                    type=NodeTypeLegacy.KEY,
                    str_="FUNC",
                    nonterminal=None,
                    terminal=None,
                    nextNodes=[],
                ),
                "n_2": NodeLegacy(
                    type=NodeTypeLegacy.TERMINAL,
                    str_="ident",
                    nonterminal=None,
                    terminal="ident",
                    nextNodes=[],
                ),
                "n_3": NodeLegacy(
                    type=NodeTypeLegacy.KEY,
                    str_="(",
                    nonterminal=None,
                    terminal=None,
                    nextNodes=[],
                ),
                "n_4": NodeLegacy(
                    type=NodeTypeLegacy.NONTERMINAL,
                    str_="ParamDecl",
                    nonterminal="ParamDecl",
                    terminal=None,
                    nextNodes=[],
                ),
                "n_5": NodeLegacy(
                    type=NodeTypeLegacy.KEY,
                    str_=",",
                    nonterminal=None,
                    terminal=None,
                    nextNodes=[],
                ),
                "n_6": NodeLegacy(
                    type=NodeTypeLegacy.KEY,
                    str_=")",
                    nonterminal=None,
                    terminal=None,
                    nextNodes=[],
                ),
                "n_7": NodeLegacy(
                    type=NodeTypeLegacy.KEY,
                    str_=":",
                    nonterminal=None,
                    terminal=None,
                    nextNodes=[],
                ),
                "n_8": NodeLegacy(
                    type=NodeTypeLegacy.NONTERMINAL,
                    str_="TypeDecl",
                    nonterminal="TypeDecl",
                    terminal=None,
                    nextNodes=[],
                ),
                "n_9": NodeLegacy(
                    type=NodeTypeLegacy.NONTERMINAL,
                    str_="StatementList",
                    nonterminal="StatementList",
                    terminal=None,
                    nextNodes=[],
                ),
                "n_10": NodeLegacy(
                    type=NodeTypeLegacy.KEY,
                    str_="END",
                    nonterminal=None,
                    terminal=None,
                    nextNodes=[],
                ),
            },
            edges=[
                ("n_1", "n_2", ""),
                ("n_2", "n_3", ""),
                ("n_4", "n_5", ""),
                ("n_5", "n_4", ""),
                ("n_3", "n_4", ""),
                ("n_3", "n_6", ""),
                ("n_4", "n_6", ""),
                ("n_6", "n_7", ""),
                ("n_7", "n_8", ""),
                ("n_8", "n_9", ""),
                ("n_9", "n_10", ""),
                ("start", "n_1", ""),
                ("n_10", "end", ""),
            ],
        ),
        RuleGraph(
            name="ProcBlock",
            nodes={
                "start": NodeLegacy(
                    type=NodeTypeLegacy.START,
                    str_="ProcBlock",
                    nonterminal=None,
                    terminal=None,
                    nextNodes=[],
                ),
                "end": NodeLegacy(
                    type=NodeTypeLegacy.END,
                    str_="",
                    nonterminal=None,
                    terminal=None,
                    nextNodes=[],
                ),
                "n_1": NodeLegacy(
                    type=NodeTypeLegacy.KEY,
                    str_="PROC",
                    nonterminal=None,
                    terminal=None,
                    nextNodes=[],
                ),
                "n_2": NodeLegacy(
                    type=NodeTypeLegacy.TERMINAL,
                    str_="ident",
                    nonterminal=None,
                    terminal="ident",
                    nextNodes=[],
                ),
                "n_3": NodeLegacy(
                    type=NodeTypeLegacy.KEY,
                    str_="(",
                    nonterminal=None,
                    terminal=None,
                    nextNodes=[],
                ),
                "n_4": NodeLegacy(
                    type=NodeTypeLegacy.NONTERMINAL,
                    str_="ParamDecl",
                    nonterminal="ParamDecl",
                    terminal=None,
                    nextNodes=[],
                ),
                "n_5": NodeLegacy(
                    type=NodeTypeLegacy.KEY,
                    str_=",",
                    nonterminal=None,
                    terminal=None,
                    nextNodes=[],
                ),
                "n_6": NodeLegacy(
                    type=NodeTypeLegacy.KEY,
                    str_=")",
                    nonterminal=None,
                    terminal=None,
                    nextNodes=[],
                ),
                "n_7": NodeLegacy(
                    type=NodeTypeLegacy.NONTERMINAL,
                    str_="StatementList",
                    nonterminal="StatementList",
                    terminal=None,
                    nextNodes=[],
                ),
                "n_8": NodeLegacy(
                    type=NodeTypeLegacy.KEY,
                    str_="END",
                    nonterminal=None,
                    terminal=None,
                    nextNodes=[],
                ),
            },
            edges=[
                ("n_1", "n_2", ""),
                ("n_2", "n_3", ""),
                ("n_4", "n_5", ""),
                ("n_5", "n_4", ""),
                ("n_3", "n_4", ""),
                ("n_3", "n_6", ""),
                ("n_4", "n_6", ""),
                ("n_6", "n_7", ""),
                ("n_7", "n_8", ""),
                ("start", "n_1", ""),
                ("n_8", "end", ""),
            ],
        ),
        RuleGraph(
            name="IterBlock",
            nodes={
                "start": NodeLegacy(
                    type=NodeTypeLegacy.START,
                    str_="IterBlock",
                    nonterminal=None,
                    terminal=None,
                    nextNodes=[],
                ),
                "end": NodeLegacy(
                    type=NodeTypeLegacy.END,
                    str_="",
                    nonterminal=None,
                    terminal=None,
                    nextNodes=[],
                ),
                "n_1": NodeLegacy(
                    type=NodeTypeLegacy.KEY,
                    str_="ITER",
                    nonterminal=None,
                    terminal=None,
                    nextNodes=[],
                ),
                "n_2": NodeLegacy(
                    type=NodeTypeLegacy.TERMINAL,
                    str_="ident",
                    nonterminal=None,
                    terminal="ident",
                    nextNodes=[],
                ),
                "n_3": NodeLegacy(
                    type=NodeTypeLegacy.KEY,
                    str_="(",
                    nonterminal=None,
                    terminal=None,
                    nextNodes=[],
                ),
                "n_4": NodeLegacy(
                    type=NodeTypeLegacy.NONTERMINAL,
                    str_="ParamDecl",
                    nonterminal="ParamDecl",
                    terminal=None,
                    nextNodes=[],
                ),
                "n_5": NodeLegacy(
                    type=NodeTypeLegacy.KEY,
                    str_=",",
                    nonterminal=None,
                    terminal=None,
                    nextNodes=[],
                ),
                "n_6": NodeLegacy(
                    type=NodeTypeLegacy.KEY,
                    str_=")",
                    nonterminal=None,
                    terminal=None,
                    nextNodes=[],
                ),
                "n_7": NodeLegacy(
                    type=NodeTypeLegacy.KEY,
                    str_=":",
                    nonterminal=None,
                    terminal=None,
                    nextNodes=[],
                ),
                "n_8": NodeLegacy(
                    type=NodeTypeLegacy.NONTERMINAL,
                    str_="TypeDecl",
                    nonterminal="TypeDecl",
                    terminal=None,
                    nextNodes=[],
                ),
                "n_9": NodeLegacy(
                    type=NodeTypeLegacy.NONTERMINAL,
                    str_="StatementList",
                    nonterminal="StatementList",
                    terminal=None,
                    nextNodes=[],
                ),
                "n_10": NodeLegacy(
                    type=NodeTypeLegacy.KEY,
                    str_="END",
                    nonterminal=None,
                    terminal=None,
                    nextNodes=[],
                ),
            },
            edges=[
                ("n_1", "n_2", ""),
                ("n_2", "n_3", ""),
                ("n_4", "n_5", ""),
                ("n_5", "n_4", ""),
                ("n_3", "n_4", ""),
                ("n_3", "n_6", ""),
                ("n_4", "n_6", ""),
                ("n_6", "n_7", ""),
                ("n_7", "n_8", ""),
                ("n_8", "n_9", ""),
                ("n_9", "n_10", ""),
                ("start", "n_1", ""),
                ("n_10", "end", ""),
            ],
        ),
        RuleGraph(
            name="AlgorithmBlock",
            nodes={
                "start": NodeLegacy(
                    type=NodeTypeLegacy.START,
                    str_="AlgorithmBlock",
                    nonterminal=None,
                    terminal=None,
                    nextNodes=[],
                ),
                "end": NodeLegacy(
                    type=NodeTypeLegacy.END,
                    str_="",
                    nonterminal=None,
                    terminal=None,
                    nextNodes=[],
                ),
                "n_1": NodeLegacy(
                    type=NodeTypeLegacy.KEY,
                    str_="ALGORITHM",
                    nonterminal=None,
                    terminal=None,
                    nextNodes=[],
                ),
                "n_2": NodeLegacy(
                    type=NodeTypeLegacy.TERMINAL,
                    str_="ident",
                    nonterminal=None,
                    terminal="ident",
                    nextNodes=[],
                ),
                "n_3": NodeLegacy(
                    type=NodeTypeLegacy.KEY,
                    str_="(",
                    nonterminal=None,
                    terminal=None,
                    nextNodes=[],
                ),
                "n_4": NodeLegacy(
                    type=NodeTypeLegacy.NONTERMINAL,
                    str_="ParamDecl",
                    nonterminal="ParamDecl",
                    terminal=None,
                    nextNodes=[],
                ),
                "n_5": NodeLegacy(
                    type=NodeTypeLegacy.KEY,
                    str_=",",
                    nonterminal=None,
                    terminal=None,
                    nextNodes=[],
                ),
                "n_6": NodeLegacy(
                    type=NodeTypeLegacy.KEY,
                    str_=")",
                    nonterminal=None,
                    terminal=None,
                    nextNodes=[],
                ),
                "n_7": NodeLegacy(
                    type=NodeTypeLegacy.KEY,
                    str_=":",
                    nonterminal=None,
                    terminal=None,
                    nextNodes=[],
                ),
                "n_8": NodeLegacy(
                    type=NodeTypeLegacy.NONTERMINAL,
                    str_="TypeDecl",
                    nonterminal="TypeDecl",
                    terminal=None,
                    nextNodes=[],
                ),
                "n_9": NodeLegacy(
                    type=NodeTypeLegacy.NONTERMINAL,
                    str_="StatementList",
                    nonterminal="StatementList",
                    terminal=None,
                    nextNodes=[],
                ),
                "n_10": NodeLegacy(
                    type=NodeTypeLegacy.KEY,
                    str_="END",
                    nonterminal=None,
                    terminal=None,
                    nextNodes=[],
                ),
            },
            edges=[
                ("n_1", "n_2", ""),
                ("n_2", "n_3", ""),
                ("n_4", "n_5", ""),
                ("n_5", "n_4", ""),
                ("n_3", "n_4", ""),
                ("n_3", "n_6", ""),
                ("n_4", "n_6", ""),
                ("n_7", "n_8", ""),
                ("n_6", "n_7", ""),
                ("n_6", "n_9", ""),
                ("n_8", "n_9", ""),
                ("n_9", "n_10", ""),
                ("start", "n_1", ""),
                ("n_10", "end", ""),
            ],
        ),
        RuleGraph(
            name="ParamDecl",
            nodes={
                "start": NodeLegacy(
                    type=NodeTypeLegacy.START,
                    str_="ParamDecl",
                    nonterminal=None,
                    terminal=None,
                    nextNodes=[],
                ),
                "end": NodeLegacy(
                    type=NodeTypeLegacy.END,
                    str_="",
                    nonterminal=None,
                    terminal=None,
                    nextNodes=[],
                ),
                "n_1": NodeLegacy(
                    type=NodeTypeLegacy.TERMINAL,
                    str_="ident",
                    nonterminal=None,
                    terminal="ident",
                    nextNodes=[],
                ),
                "n_2": NodeLegacy(
                    type=NodeTypeLegacy.KEY,
                    str_=":",
                    nonterminal=None,
                    terminal=None,
                    nextNodes=[],
                ),
                "n_3": NodeLegacy(
                    type=NodeTypeLegacy.NONTERMINAL,
                    str_="TypeDecl",
                    nonterminal="TypeDecl",
                    terminal=None,
                    nextNodes=[],
                ),
            },
            edges=[
                ("n_1", "n_2", ""),
                ("n_2", "n_3", ""),
                ("start", "n_1", ""),
                ("n_3", "end", ""),
            ],
        ),
        RuleGraph(
            name="PrimitiveType",
            nodes={
                "start": NodeLegacy(
                    type=NodeTypeLegacy.START,
                    str_="PrimitiveType",
                    nonterminal=None,
                    terminal=None,
                    nextNodes=[],
                ),
                "end": NodeLegacy(
                    type=NodeTypeLegacy.END,
                    str_="",
                    nonterminal=None,
                    terminal=None,
                    nextNodes=[],
                ),
                "n_1": NodeLegacy(
                    type=NodeTypeLegacy.KEY,
                    str_="int",
                    nonterminal=None,
                    terminal=None,
                    nextNodes=[],
                ),
                "n_2": NodeLegacy(
                    type=NodeTypeLegacy.KEY,
                    str_="bool",
                    nonterminal=None,
                    terminal=None,
                    nextNodes=[],
                ),
                "n_3": NodeLegacy(
                    type=NodeTypeLegacy.TERMINAL,
                    str_="string",
                    nonterminal=None,
                    terminal="string",
                    nextNodes=[],
                ),
                "n_4": NodeLegacy(
                    type=NodeTypeLegacy.KEY,
                    str_="float",
                    nonterminal=None,
                    terminal=None,
                    nextNodes=[],
                ),
            },
            edges=[
                ("start", "n_3", ""),
                ("start", "n_1", ""),
                ("start", "n_4", ""),
                ("start", "n_2", ""),
                ("n_3", "end", ""),
                ("n_1", "end", ""),
                ("n_4", "end", ""),
                ("n_2", "end", ""),
            ],
        ),
        RuleGraph(
            name="TypeDecl",
            nodes={
                "start": NodeLegacy(
                    type=NodeTypeLegacy.START,
                    str_="TypeDecl",
                    nonterminal=None,
                    terminal=None,
                    nextNodes=[],
                ),
                "end": NodeLegacy(
                    type=NodeTypeLegacy.END,
                    str_="",
                    nonterminal=None,
                    terminal=None,
                    nextNodes=[],
                ),
                "n_1": NodeLegacy(
                    type=NodeTypeLegacy.NONTERMINAL,
                    str_="PrimitiveType",
                    nonterminal="PrimitiveType",
                    terminal=None,
                    nextNodes=[],
                ),
                "n_2": NodeLegacy(
                    type=NodeTypeLegacy.KEY,
                    str_="list",
                    nonterminal=None,
                    terminal=None,
                    nextNodes=[],
                ),
                "n_3": NodeLegacy(
                    type=NodeTypeLegacy.KEY,
                    str_="of",
                    nonterminal=None,
                    terminal=None,
                    nextNodes=[],
                ),
                "n_4": NodeLegacy(
                    type=NodeTypeLegacy.NONTERMINAL,
                    str_="TypeDecl",
                    nonterminal="TypeDecl",
                    terminal=None,
                    nextNodes=[],
                ),
                "n_5": NodeLegacy(
                    type=NodeTypeLegacy.KEY,
                    str_="array",
                    nonterminal=None,
                    terminal=None,
                    nextNodes=[],
                ),
                "n_6": NodeLegacy(
                    type=NodeTypeLegacy.KEY,
                    str_="[",
                    nonterminal=None,
                    terminal=None,
                    nextNodes=[],
                ),
                "n_7": NodeLegacy(
                    type=NodeTypeLegacy.NONTERMINAL,
                    str_="Expression",
                    nonterminal="Expression",
                    terminal=None,
                    nextNodes=[],
                ),
                "n_8": NodeLegacy(
                    type=NodeTypeLegacy.KEY,
                    str_=",",
                    nonterminal=None,
                    terminal=None,
                    nextNodes=[],
                ),
                "n_9": NodeLegacy(
                    type=NodeTypeLegacy.KEY,
                    str_="]",
                    nonterminal=None,
                    terminal=None,
                    nextNodes=[],
                ),
                "n_10": NodeLegacy(
                    type=NodeTypeLegacy.KEY,
                    str_="of",
                    nonterminal=None,
                    terminal=None,
                    nextNodes=[],
                ),
                "n_11": NodeLegacy(
                    type=NodeTypeLegacy.NONTERMINAL,
                    str_="TypeDecl",
                    nonterminal="TypeDecl",
                    terminal=None,
                    nextNodes=[],
                ),
            },
            edges=[
                ("n_2", "n_3", ""),
                ("n_3", "n_4", ""),
                ("n_5", "n_6", ""),
                ("n_7", "n_8", ""),
                ("n_8", "n_7", ""),
                ("n_6", "n_7", ""),
                ("n_6", "n_9", ""),
                ("n_7", "n_9", ""),
                ("n_9", "n_10", ""),
                ("n_10", "n_11", ""),
                ("start", "n_5", ""),
                ("start", "n_1", ""),
                ("start", "n_2", ""),
                ("n_1", "end", ""),
                ("n_4", "end", ""),
                ("n_11", "end", ""),
            ],
        ),
        RuleGraph(
            name="StatementList",
            nodes={
                "start": NodeLegacy(
                    type=NodeTypeLegacy.START,
                    str_="StatementList",
                    nonterminal=None,
                    terminal=None,
                    nextNodes=[],
                ),
                "end": NodeLegacy(
                    type=NodeTypeLegacy.END,
                    str_="",
                    nonterminal=None,
                    terminal=None,
                    nextNodes=[],
                ),
                "n_1": NodeLegacy(
                    type=NodeTypeLegacy.NONTERMINAL,
                    str_="Statement",
                    nonterminal="Statement",
                    terminal=None,
                    nextNodes=[],
                ),
            },
            edges=[
                ("n_1", "n_1", ""),
                ("start", "n_1", ""),
                ("n_1", "end", ""),
                ("start", "end", ""),
            ],
        ),
        RuleGraph(
            name="Statement",
            nodes={
                "start": NodeLegacy(
                    type=NodeTypeLegacy.START,
                    str_="Statement",
                    nonterminal=None,
                    terminal=None,
                    nextNodes=[],
                ),
                "end": NodeLegacy(
                    type=NodeTypeLegacy.END,
                    str_="",
                    nonterminal=None,
                    terminal=None,
                    nextNodes=[],
                ),
                "n_1": NodeLegacy(
                    type=NodeTypeLegacy.NONTERMINAL,
                    str_="Assignment",
                    nonterminal="Assignment",
                    terminal=None,
                    nextNodes=[],
                ),
                "n_2": NodeLegacy(
                    type=NodeTypeLegacy.NONTERMINAL,
                    str_="IfStatement",
                    nonterminal="IfStatement",
                    terminal=None,
                    nextNodes=[],
                ),
                "n_3": NodeLegacy(
                    type=NodeTypeLegacy.NONTERMINAL,
                    str_="WhileStatement",
                    nonterminal="WhileStatement",
                    terminal=None,
                    nextNodes=[],
                ),
                "n_4": NodeLegacy(
                    type=NodeTypeLegacy.NONTERMINAL,
                    str_="ForStatement",
                    nonterminal="ForStatement",
                    terminal=None,
                    nextNodes=[],
                ),
                "n_5": NodeLegacy(
                    type=NodeTypeLegacy.NONTERMINAL,
                    str_="ForInStatement",
                    nonterminal="ForInStatement",
                    terminal=None,
                    nextNodes=[],
                ),
                "n_6": NodeLegacy(
                    type=NodeTypeLegacy.NONTERMINAL,
                    str_="CallStatement",
                    nonterminal="CallStatement",
                    terminal=None,
                    nextNodes=[],
                ),
                "n_7": NodeLegacy(
                    type=NodeTypeLegacy.NONTERMINAL,
                    str_="ReturnStatement",
                    nonterminal="ReturnStatement",
                    terminal=None,
                    nextNodes=[],
                ),
                "n_8": NodeLegacy(
                    type=NodeTypeLegacy.NONTERMINAL,
                    str_="YieldStatement",
                    nonterminal="YieldStatement",
                    terminal=None,
                    nextNodes=[],
                ),
                "n_9": NodeLegacy(
                    type=NodeTypeLegacy.NONTERMINAL,
                    str_="ExitStatement",
                    nonterminal="ExitStatement",
                    terminal=None,
                    nextNodes=[],
                ),
            },
            edges=[
                ("start", "n_6", ""),
                ("start", "n_5", ""),
                ("start", "n_9", ""),
                ("start", "n_8", ""),
                ("start", "n_3", ""),
                ("start", "n_4", ""),
                ("start", "n_1", ""),
                ("start", "n_2", ""),
                ("start", "n_7", ""),
                ("n_6", "end", ""),
                ("n_5", "end", ""),
                ("n_9", "end", ""),
                ("n_8", "end", ""),
                ("n_3", "end", ""),
                ("n_4", "end", ""),
                ("n_1", "end", ""),
                ("n_2", "end", ""),
                ("n_7", "end", ""),
            ],
        ),
        RuleGraph(
            name="Assignment",
            nodes={
                "start": NodeLegacy(
                    type=NodeTypeLegacy.START,
                    str_="Assignment",
                    nonterminal=None,
                    terminal=None,
                    nextNodes=[],
                ),
                "end": NodeLegacy(
                    type=NodeTypeLegacy.END,
                    str_="",
                    nonterminal=None,
                    terminal=None,
                    nextNodes=[],
                ),
                "n_1": NodeLegacy(
                    type=NodeTypeLegacy.TERMINAL,
                    str_="ident",
                    nonterminal=None,
                    terminal="ident",
                    nextNodes=[],
                ),
                "n_2": NodeLegacy(
                    type=NodeTypeLegacy.KEY,
                    str_="[",
                    nonterminal=None,
                    terminal=None,
                    nextNodes=[],
                ),
                "n_3": NodeLegacy(
                    type=NodeTypeLegacy.NONTERMINAL,
                    str_="Expression",
                    nonterminal="Expression",
                    terminal=None,
                    nextNodes=[],
                ),
                "n_4": NodeLegacy(
                    type=NodeTypeLegacy.KEY,
                    str_=",",
                    nonterminal=None,
                    terminal=None,
                    nextNodes=[],
                ),
                "n_5": NodeLegacy(
                    type=NodeTypeLegacy.KEY,
                    str_="]",
                    nonterminal=None,
                    terminal=None,
                    nextNodes=[],
                ),
                "n_6": NodeLegacy(
                    type=NodeTypeLegacy.KEY,
                    str_="=",
                    nonterminal=None,
                    terminal=None,
                    nextNodes=[],
                ),
                "n_7": NodeLegacy(
                    type=NodeTypeLegacy.NONTERMINAL,
                    str_="Expression",
                    nonterminal="Expression",
                    terminal=None,
                    nextNodes=[],
                ),
            },
            edges=[
                ("n_3", "n_4", ""),
                ("n_4", "n_3", ""),
                ("n_2", "n_3", ""),
                ("n_3", "n_5", ""),
                ("n_2", "n_5", ""),
                ("n_1", "n_2", ""),
                ("n_5", "n_6", ""),
                ("n_1", "n_6", ""),
                ("n_6", "n_7", ""),
                ("start", "n_1", ""),
                ("n_7", "end", ""),
            ],
        ),
        RuleGraph(
            name="IfStatement",
            nodes={
                "start": NodeLegacy(
                    type=NodeTypeLegacy.START,
                    str_="IfStatement",
                    nonterminal=None,
                    terminal=None,
                    nextNodes=[],
                ),
                "end": NodeLegacy(
                    type=NodeTypeLegacy.END,
                    str_="",
                    nonterminal=None,
                    terminal=None,
                    nextNodes=[],
                ),
                "n_1": NodeLegacy(
                    type=NodeTypeLegacy.KEY,
                    str_="IF",
                    nonterminal=None,
                    terminal=None,
                    nextNodes=[],
                ),
                "n_2": NodeLegacy(
                    type=NodeTypeLegacy.NONTERMINAL,
                    str_="Condition",
                    nonterminal="Condition",
                    terminal=None,
                    nextNodes=[],
                ),
                "n_3": NodeLegacy(
                    type=NodeTypeLegacy.KEY,
                    str_="THEN",
                    nonterminal=None,
                    terminal=None,
                    nextNodes=[],
                ),
                "n_4": NodeLegacy(
                    type=NodeTypeLegacy.NONTERMINAL,
                    str_="StatementList",
                    nonterminal="StatementList",
                    terminal=None,
                    nextNodes=[],
                ),
                "n_5": NodeLegacy(
                    type=NodeTypeLegacy.KEY,
                    str_="ELSE",
                    nonterminal=None,
                    terminal=None,
                    nextNodes=[],
                ),
                "n_6": NodeLegacy(
                    type=NodeTypeLegacy.NONTERMINAL,
                    str_="StatementList",
                    nonterminal="StatementList",
                    terminal=None,
                    nextNodes=[],
                ),
                "n_7": NodeLegacy(
                    type=NodeTypeLegacy.KEY,
                    str_="ENDIF",
                    nonterminal=None,
                    terminal=None,
                    nextNodes=[],
                ),
            },
            edges=[
                ("n_1", "n_2", ""),
                ("n_2", "n_3", ""),
                ("n_3", "n_4", ""),
                ("n_5", "n_6", ""),
                ("n_4", "n_5", ""),
                ("n_6", "n_7", ""),
                ("n_4", "n_7", ""),
                ("start", "n_1", ""),
                ("n_7", "end", ""),
            ],
        ),
        RuleGraph(
            name="WhileStatement",
            nodes={
                "start": NodeLegacy(
                    type=NodeTypeLegacy.START,
                    str_="WhileStatement",
                    nonterminal=None,
                    terminal=None,
                    nextNodes=[],
                ),
                "end": NodeLegacy(
                    type=NodeTypeLegacy.END,
                    str_="",
                    nonterminal=None,
                    terminal=None,
                    nextNodes=[],
                ),
                "n_1": NodeLegacy(
                    type=NodeTypeLegacy.KEY,
                    str_="WHILE",
                    nonterminal=None,
                    terminal=None,
                    nextNodes=[],
                ),
                "n_2": NodeLegacy(
                    type=NodeTypeLegacy.NONTERMINAL,
                    str_="Condition",
                    nonterminal="Condition",
                    terminal=None,
                    nextNodes=[],
                ),
                "n_3": NodeLegacy(
                    type=NodeTypeLegacy.KEY,
                    str_="DO",
                    nonterminal=None,
                    terminal=None,
                    nextNodes=[],
                ),
                "n_4": NodeLegacy(
                    type=NodeTypeLegacy.NONTERMINAL,
                    str_="StatementList",
                    nonterminal="StatementList",
                    terminal=None,
                    nextNodes=[],
                ),
                "n_5": NodeLegacy(
                    type=NodeTypeLegacy.KEY,
                    str_="ENDWHILE",
                    nonterminal=None,
                    terminal=None,
                    nextNodes=[],
                ),
            },
            edges=[
                ("n_1", "n_2", ""),
                ("n_2", "n_3", ""),
                ("n_3", "n_4", ""),
                ("n_4", "n_5", ""),
                ("start", "n_1", ""),
                ("n_5", "end", ""),
            ],
        ),
        RuleGraph(
            name="ForStatement",
            nodes={
                "start": NodeLegacy(
                    type=NodeTypeLegacy.START,
                    str_="ForStatement",
                    nonterminal=None,
                    terminal=None,
                    nextNodes=[],
                ),
                "end": NodeLegacy(
                    type=NodeTypeLegacy.END,
                    str_="",
                    nonterminal=None,
                    terminal=None,
                    nextNodes=[],
                ),
                "n_1": NodeLegacy(
                    type=NodeTypeLegacy.KEY,
                    str_="FOR",
                    nonterminal=None,
                    terminal=None,
                    nextNodes=[],
                ),
                "n_2": NodeLegacy(
                    type=NodeTypeLegacy.TERMINAL,
                    str_="ident",
                    nonterminal=None,
                    terminal="ident",
                    nextNodes=[],
                ),
                "n_3": NodeLegacy(
                    type=NodeTypeLegacy.KEY,
                    str_="FROM",
                    nonterminal=None,
                    terminal=None,
                    nextNodes=[],
                ),
                "n_4": NodeLegacy(
                    type=NodeTypeLegacy.NONTERMINAL,
                    str_="Expression",
                    nonterminal="Expression",
                    terminal=None,
                    nextNodes=[],
                ),
                "n_5": NodeLegacy(
                    type=NodeTypeLegacy.KEY,
                    str_="TO",
                    nonterminal=None,
                    terminal=None,
                    nextNodes=[],
                ),
                "n_6": NodeLegacy(
                    type=NodeTypeLegacy.NONTERMINAL,
                    str_="Expression",
                    nonterminal="Expression",
                    terminal=None,
                    nextNodes=[],
                ),
                "n_7": NodeLegacy(
                    type=NodeTypeLegacy.KEY,
                    str_="DO",
                    nonterminal=None,
                    terminal=None,
                    nextNodes=[],
                ),
                "n_8": NodeLegacy(
                    type=NodeTypeLegacy.NONTERMINAL,
                    str_="StatementList",
                    nonterminal="StatementList",
                    terminal=None,
                    nextNodes=[],
                ),
                "n_9": NodeLegacy(
                    type=NodeTypeLegacy.KEY,
                    str_="ENDFOR",
                    nonterminal=None,
                    terminal=None,
                    nextNodes=[],
                ),
            },
            edges=[
                ("n_1", "n_2", ""),
                ("n_2", "n_3", ""),
                ("n_3", "n_4", ""),
                ("n_4", "n_5", ""),
                ("n_5", "n_6", ""),
                ("n_6", "n_7", ""),
                ("n_7", "n_8", ""),
                ("n_8", "n_9", ""),
                ("start", "n_1", ""),
                ("n_9", "end", ""),
            ],
        ),
        RuleGraph(
            name="ForInStatement",
            nodes={
                "start": NodeLegacy(
                    type=NodeTypeLegacy.START,
                    str_="ForInStatement",
                    nonterminal=None,
                    terminal=None,
                    nextNodes=[],
                ),
                "end": NodeLegacy(
                    type=NodeTypeLegacy.END,
                    str_="",
                    nonterminal=None,
                    terminal=None,
                    nextNodes=[],
                ),
                "n_1": NodeLegacy(
                    type=NodeTypeLegacy.KEY,
                    str_="FOR",
                    nonterminal=None,
                    terminal=None,
                    nextNodes=[],
                ),
                "n_2": NodeLegacy(
                    type=NodeTypeLegacy.TERMINAL,
                    str_="ident",
                    nonterminal=None,
                    terminal="ident",
                    nextNodes=[],
                ),
                "n_3": NodeLegacy(
                    type=NodeTypeLegacy.KEY,
                    str_="IN",
                    nonterminal=None,
                    terminal=None,
                    nextNodes=[],
                ),
                "n_4": NodeLegacy(
                    type=NodeTypeLegacy.NONTERMINAL,
                    str_="Expression",
                    nonterminal="Expression",
                    terminal=None,
                    nextNodes=[],
                ),
                "n_5": NodeLegacy(
                    type=NodeTypeLegacy.KEY,
                    str_="DO",
                    nonterminal=None,
                    terminal=None,
                    nextNodes=[],
                ),
                "n_6": NodeLegacy(
                    type=NodeTypeLegacy.NONTERMINAL,
                    str_="StatementList",
                    nonterminal="StatementList",
                    terminal=None,
                    nextNodes=[],
                ),
                "n_7": NodeLegacy(
                    type=NodeTypeLegacy.KEY,
                    str_="ENDFOR",
                    nonterminal=None,
                    terminal=None,
                    nextNodes=[],
                ),
            },
            edges=[
                ("n_1", "n_2", ""),
                ("n_2", "n_3", ""),
                ("n_3", "n_4", ""),
                ("n_4", "n_5", ""),
                ("n_5", "n_6", ""),
                ("n_6", "n_7", ""),
                ("start", "n_1", ""),
                ("n_7", "end", ""),
            ],
        ),
        RuleGraph(
            name="CallStatement",
            nodes={
                "start": NodeLegacy(
                    type=NodeTypeLegacy.START,
                    str_="CallStatement",
                    nonterminal=None,
                    terminal=None,
                    nextNodes=[],
                ),
                "end": NodeLegacy(
                    type=NodeTypeLegacy.END,
                    str_="",
                    nonterminal=None,
                    terminal=None,
                    nextNodes=[],
                ),
                "n_1": NodeLegacy(
                    type=NodeTypeLegacy.NONTERMINAL,
                    str_="CallExpr",
                    nonterminal="CallExpr",
                    terminal=None,
                    nextNodes=[],
                ),
            },
            edges=[("start", "n_1", ""), ("n_1", "end", "")],
        ),
        RuleGraph(
            name="ReturnStatement",
            nodes={
                "start": NodeLegacy(
                    type=NodeTypeLegacy.START,
                    str_="ReturnStatement",
                    nonterminal=None,
                    terminal=None,
                    nextNodes=[],
                ),
                "end": NodeLegacy(
                    type=NodeTypeLegacy.END,
                    str_="",
                    nonterminal=None,
                    terminal=None,
                    nextNodes=[],
                ),
                "n_1": NodeLegacy(
                    type=NodeTypeLegacy.KEY,
                    str_="RETURN",
                    nonterminal=None,
                    terminal=None,
                    nextNodes=[],
                ),
                "n_2": NodeLegacy(
                    type=NodeTypeLegacy.NONTERMINAL,
                    str_="Expression",
                    nonterminal="Expression",
                    terminal=None,
                    nextNodes=[],
                ),
            },
            edges=[
                ("n_1", "n_2", ""),
                ("start", "n_1", ""),
                ("n_1", "end", ""),
                ("n_2", "end", ""),
            ],
        ),
        RuleGraph(
            name="YieldStatement",
            nodes={
                "start": NodeLegacy(
                    type=NodeTypeLegacy.START,
                    str_="YieldStatement",
                    nonterminal=None,
                    terminal=None,
                    nextNodes=[],
                ),
                "end": NodeLegacy(
                    type=NodeTypeLegacy.END,
                    str_="",
                    nonterminal=None,
                    terminal=None,
                    nextNodes=[],
                ),
                "n_1": NodeLegacy(
                    type=NodeTypeLegacy.KEY,
                    str_="YIELD",
                    nonterminal=None,
                    terminal=None,
                    nextNodes=[],
                ),
                "n_2": NodeLegacy(
                    type=NodeTypeLegacy.NONTERMINAL,
                    str_="Expression",
                    nonterminal="Expression",
                    terminal=None,
                    nextNodes=[],
                ),
            },
            edges=[("n_1", "n_2", ""), ("start", "n_1", ""), ("n_2", "end", "")],
        ),
        RuleGraph(
            name="ExitStatement",
            nodes={
                "start": NodeLegacy(
                    type=NodeTypeLegacy.START,
                    str_="ExitStatement",
                    nonterminal=None,
                    terminal=None,
                    nextNodes=[],
                ),
                "end": NodeLegacy(
                    type=NodeTypeLegacy.END,
                    str_="",
                    nonterminal=None,
                    terminal=None,
                    nextNodes=[],
                ),
                "n_1": NodeLegacy(
                    type=NodeTypeLegacy.KEY,
                    str_="EXIT",
                    nonterminal=None,
                    terminal=None,
                    nextNodes=[],
                ),
            },
            edges=[("start", "n_1", ""), ("n_1", "end", "")],
        ),
        RuleGraph(
            name="Condition",
            nodes={
                "start": NodeLegacy(
                    type=NodeTypeLegacy.START,
                    str_="Condition",
                    nonterminal=None,
                    terminal=None,
                    nextNodes=[],
                ),
                "end": NodeLegacy(
                    type=NodeTypeLegacy.END,
                    str_="",
                    nonterminal=None,
                    terminal=None,
                    nextNodes=[],
                ),
                "n_1": NodeLegacy(
                    type=NodeTypeLegacy.NONTERMINAL,
                    str_="LogicalTerm",
                    nonterminal="LogicalTerm",
                    terminal=None,
                    nextNodes=[],
                ),
                "n_2": NodeLegacy(
                    type=NodeTypeLegacy.KEY,
                    str_="OR",
                    nonterminal=None,
                    terminal=None,
                    nextNodes=[],
                ),
                "n_3": NodeLegacy(
                    type=NodeTypeLegacy.NONTERMINAL,
                    str_="LogicalTerm",
                    nonterminal="LogicalTerm",
                    terminal=None,
                    nextNodes=[],
                ),
            },
            edges=[
                ("n_2", "n_3", ""),
                ("n_3", "n_2", ""),
                ("n_1", "n_2", ""),
                ("start", "n_1", ""),
                ("n_3", "end", ""),
                ("n_1", "end", ""),
            ],
        ),
        RuleGraph(
            name="LogicalTerm",
            nodes={
                "start": NodeLegacy(
                    type=NodeTypeLegacy.START,
                    str_="LogicalTerm",
                    nonterminal=None,
                    terminal=None,
                    nextNodes=[],
                ),
                "end": NodeLegacy(
                    type=NodeTypeLegacy.END,
                    str_="",
                    nonterminal=None,
                    terminal=None,
                    nextNodes=[],
                ),
                "n_1": NodeLegacy(
                    type=NodeTypeLegacy.NONTERMINAL,
                    str_="LogicalFactor",
                    nonterminal="LogicalFactor",
                    terminal=None,
                    nextNodes=[],
                ),
                "n_2": NodeLegacy(
                    type=NodeTypeLegacy.KEY,
                    str_="AND",
                    nonterminal=None,
                    terminal=None,
                    nextNodes=[],
                ),
                "n_3": NodeLegacy(
                    type=NodeTypeLegacy.NONTERMINAL,
                    str_="LogicalFactor",
                    nonterminal="LogicalFactor",
                    terminal=None,
                    nextNodes=[],
                ),
            },
            edges=[
                ("n_2", "n_3", ""),
                ("n_3", "n_2", ""),
                ("n_1", "n_2", ""),
                ("start", "n_1", ""),
                ("n_3", "end", ""),
                ("n_1", "end", ""),
            ],
        ),
        RuleGraph(
            name="LogicalFactor",
            nodes={
                "start": NodeLegacy(
                    type=NodeTypeLegacy.START,
                    str_="LogicalFactor",
                    nonterminal=None,
                    terminal=None,
                    nextNodes=[],
                ),
                "end": NodeLegacy(
                    type=NodeTypeLegacy.END,
                    str_="",
                    nonterminal=None,
                    terminal=None,
                    nextNodes=[],
                ),
                "n_1": NodeLegacy(
                    type=NodeTypeLegacy.KEY,
                    str_="NOT",
                    nonterminal=None,
                    terminal=None,
                    nextNodes=[],
                ),
                "n_2": NodeLegacy(
                    type=NodeTypeLegacy.NONTERMINAL,
                    str_="Comparison",
                    nonterminal="Comparison",
                    terminal=None,
                    nextNodes=[],
                ),
                "n_3": NodeLegacy(
                    type=NodeTypeLegacy.KEY,
                    str_="(",
                    nonterminal=None,
                    terminal=None,
                    nextNodes=[],
                ),
                "n_4": NodeLegacy(
                    type=NodeTypeLegacy.NONTERMINAL,
                    str_="Condition",
                    nonterminal="Condition",
                    terminal=None,
                    nextNodes=[],
                ),
                "n_5": NodeLegacy(
                    type=NodeTypeLegacy.KEY,
                    str_=")",
                    nonterminal=None,
                    terminal=None,
                    nextNodes=[],
                ),
            },
            edges=[
                ("n_3", "n_4", ""),
                ("n_4", "n_5", ""),
                ("n_1", "n_3", ""),
                ("n_1", "n_2", ""),
                ("start", "n_3", ""),
                ("start", "n_1", ""),
                ("start", "n_2", ""),
                ("n_5", "end", ""),
                ("n_2", "end", ""),
            ],
        ),
        RuleGraph(
            name="Comparison",
            nodes={
                "start": NodeLegacy(
                    type=NodeTypeLegacy.START,
                    str_="Comparison",
                    nonterminal=None,
                    terminal=None,
                    nextNodes=[],
                ),
                "end": NodeLegacy(
                    type=NodeTypeLegacy.END,
                    str_="",
                    nonterminal=None,
                    terminal=None,
                    nextNodes=[],
                ),
                "n_1": NodeLegacy(
                    type=NodeTypeLegacy.NONTERMINAL,
                    str_="Expression",
                    nonterminal="Expression",
                    terminal=None,
                    nextNodes=[],
                ),
                "n_2": NodeLegacy(
                    type=NodeTypeLegacy.KEY,
                    str_="<",
                    nonterminal=None,
                    terminal=None,
                    nextNodes=[],
                ),
                "n_3": NodeLegacy(
                    type=NodeTypeLegacy.KEY,
                    str_=">",
                    nonterminal=None,
                    terminal=None,
                    nextNodes=[],
                ),
                "n_4": NodeLegacy(
                    type=NodeTypeLegacy.KEY,
                    str_="<=",
                    nonterminal=None,
                    terminal=None,
                    nextNodes=[],
                ),
                "n_5": NodeLegacy(
                    type=NodeTypeLegacy.KEY,
                    str_=">=",
                    nonterminal=None,
                    terminal=None,
                    nextNodes=[],
                ),
                "n_6": NodeLegacy(
                    type=NodeTypeLegacy.KEY,
                    str_="==",
                    nonterminal=None,
                    terminal=None,
                    nextNodes=[],
                ),
                "n_7": NodeLegacy(
                    type=NodeTypeLegacy.KEY,
                    str_="!=",
                    nonterminal=None,
                    terminal=None,
                    nextNodes=[],
                ),
                "n_8": NodeLegacy(
                    type=NodeTypeLegacy.KEY,
                    str_="IN",
                    nonterminal=None,
                    terminal=None,
                    nextNodes=[],
                ),
                "n_9": NodeLegacy(
                    type=NodeTypeLegacy.NONTERMINAL,
                    str_="Expression",
                    nonterminal="Expression",
                    terminal=None,
                    nextNodes=[],
                ),
            },
            edges=[
                ("n_6", "n_9", ""),
                ("n_5", "n_9", ""),
                ("n_8", "n_9", ""),
                ("n_2", "n_9", ""),
                ("n_3", "n_9", ""),
                ("n_4", "n_9", ""),
                ("n_7", "n_9", ""),
                ("n_1", "n_6", ""),
                ("n_1", "n_5", ""),
                ("n_1", "n_8", ""),
                ("n_1", "n_2", ""),
                ("n_1", "n_3", ""),
                ("n_1", "n_4", ""),
                ("n_1", "n_7", ""),
                ("start", "n_1", ""),
                ("n_9", "end", ""),
                ("n_1", "end", ""),
            ],
        ),
        RuleGraph(
            name="Expression",
            nodes={
                "start": NodeLegacy(
                    type=NodeTypeLegacy.START,
                    str_="Expression",
                    nonterminal=None,
                    terminal=None,
                    nextNodes=[],
                ),
                "end": NodeLegacy(
                    type=NodeTypeLegacy.END,
                    str_="",
                    nonterminal=None,
                    terminal=None,
                    nextNodes=[],
                ),
                "n_1": NodeLegacy(
                    type=NodeTypeLegacy.NONTERMINAL,
                    str_="Term",
                    nonterminal="Term",
                    terminal=None,
                    nextNodes=[],
                ),
                "n_2": NodeLegacy(
                    type=NodeTypeLegacy.KEY,
                    str_="+",
                    nonterminal=None,
                    terminal=None,
                    nextNodes=[],
                ),
                "n_3": NodeLegacy(
                    type=NodeTypeLegacy.KEY,
                    str_="-",
                    nonterminal=None,
                    terminal=None,
                    nextNodes=[],
                ),
            },
            edges=[
                ("n_1", "n_3", ""),
                ("n_1", "n_2", ""),
                ("n_3", "n_1", ""),
                ("n_2", "n_1", ""),
                ("start", "n_1", ""),
                ("n_1", "end", ""),
                ("start", "end", ""),
            ],
        ),
        RuleGraph(
            name="Term",
            nodes={
                "start": NodeLegacy(
                    type=NodeTypeLegacy.START,
                    str_="Term",
                    nonterminal=None,
                    terminal=None,
                    nextNodes=[],
                ),
                "end": NodeLegacy(
                    type=NodeTypeLegacy.END,
                    str_="",
                    nonterminal=None,
                    terminal=None,
                    nextNodes=[],
                ),
                "n_1": NodeLegacy(
                    type=NodeTypeLegacy.NONTERMINAL,
                    str_="Factor",
                    nonterminal="Factor",
                    terminal=None,
                    nextNodes=[],
                ),
                "n_2": NodeLegacy(
                    type=NodeTypeLegacy.KEY,
                    str_="*",
                    nonterminal=None,
                    terminal=None,
                    nextNodes=[],
                ),
                "n_3": NodeLegacy(
                    type=NodeTypeLegacy.KEY,
                    str_="/",
                    nonterminal=None,
                    terminal=None,
                    nextNodes=[],
                ),
                "n_4": NodeLegacy(
                    type=NodeTypeLegacy.KEY,
                    str_="DIV",
                    nonterminal=None,
                    terminal=None,
                    nextNodes=[],
                ),
                "n_5": NodeLegacy(
                    type=NodeTypeLegacy.KEY,
                    str_="MOD",
                    nonterminal=None,
                    terminal=None,
                    nextNodes=[],
                ),
                "n_6": NodeLegacy(
                    type=NodeTypeLegacy.NONTERMINAL,
                    str_="Factor",
                    nonterminal="Factor",
                    terminal=None,
                    nextNodes=[],
                ),
            },
            edges=[
                ("n_5", "n_6", ""),
                ("n_3", "n_6", ""),
                ("n_4", "n_6", ""),
                ("n_2", "n_6", ""),
                ("n_6", "n_5", ""),
                ("n_6", "n_3", ""),
                ("n_6", "n_4", ""),
                ("n_6", "n_2", ""),
                ("n_1", "n_5", ""),
                ("n_1", "n_3", ""),
                ("n_1", "n_4", ""),
                ("n_1", "n_2", ""),
                ("start", "n_1", ""),
                ("n_6", "end", ""),
                ("n_1", "end", ""),
            ],
        ),
        RuleGraph(
            name="Factor",
            nodes={
                "start": NodeLegacy(
                    type=NodeTypeLegacy.START,
                    str_="Factor",
                    nonterminal=None,
                    terminal=None,
                    nextNodes=[],
                ),
                "end": NodeLegacy(
                    type=NodeTypeLegacy.END,
                    str_="",
                    nonterminal=None,
                    terminal=None,
                    nextNodes=[],
                ),
                "n_1": NodeLegacy(
                    type=NodeTypeLegacy.TERMINAL,
                    str_="ident",
                    nonterminal=None,
                    terminal="ident",
                    nextNodes=[],
                ),
                "n_2": NodeLegacy(
                    type=NodeTypeLegacy.KEY,
                    str_="[",
                    nonterminal=None,
                    terminal=None,
                    nextNodes=[],
                ),
                "n_3": NodeLegacy(
                    type=NodeTypeLegacy.NONTERMINAL,
                    str_="Expression",
                    nonterminal="Expression",
                    terminal=None,
                    nextNodes=[],
                ),
                "n_4": NodeLegacy(
                    type=NodeTypeLegacy.KEY,
                    str_=",",
                    nonterminal=None,
                    terminal=None,
                    nextNodes=[],
                ),
                "n_5": NodeLegacy(
                    type=NodeTypeLegacy.KEY,
                    str_="]",
                    nonterminal=None,
                    terminal=None,
                    nextNodes=[],
                ),
                "n_6": NodeLegacy(
                    type=NodeTypeLegacy.TERMINAL,
                    str_="number",
                    nonterminal=None,
                    terminal="number",
                    nextNodes=[],
                ),
                "n_7": NodeLegacy(
                    type=NodeTypeLegacy.TERMINAL,
                    str_="string",
                    nonterminal=None,
                    terminal="string",
                    nextNodes=[],
                ),
                "n_8": NodeLegacy(
                    type=NodeTypeLegacy.KEY,
                    str_="TRUE",
                    nonterminal=None,
                    terminal=None,
                    nextNodes=[],
                ),
                "n_9": NodeLegacy(
                    type=NodeTypeLegacy.KEY,
                    str_="FALSE",
                    nonterminal=None,
                    terminal=None,
                    nextNodes=[],
                ),
                "n_10": NodeLegacy(
                    type=NodeTypeLegacy.NONTERMINAL,
                    str_="CallExpr",
                    nonterminal="CallExpr",
                    terminal=None,
                    nextNodes=[],
                ),
                "n_11": NodeLegacy(
                    type=NodeTypeLegacy.KEY,
                    str_="(",
                    nonterminal=None,
                    terminal=None,
                    nextNodes=[],
                ),
                "n_12": NodeLegacy(
                    type=NodeTypeLegacy.NONTERMINAL,
                    str_="Expression",
                    nonterminal="Expression",
                    terminal=None,
                    nextNodes=[],
                ),
                "n_13": NodeLegacy(
                    type=NodeTypeLegacy.KEY,
                    str_=")",
                    nonterminal=None,
                    terminal=None,
                    nextNodes=[],
                ),
                "n_14": NodeLegacy(
                    type=NodeTypeLegacy.NONTERMINAL,
                    str_="CollectionLiteral",
                    nonterminal="CollectionLiteral",
                    terminal=None,
                    nextNodes=[],
                ),
            },
            edges=[
                ("n_3", "n_4", ""),
                ("n_4", "n_3", ""),
                ("n_2", "n_3", ""),
                ("n_3", "n_5", ""),
                ("n_2", "n_5", ""),
                ("n_1", "n_2", ""),
                ("n_11", "n_12", ""),
                ("n_12", "n_13", ""),
                ("start", "n_6", ""),
                ("start", "n_9", ""),
                ("start", "n_1", ""),
                ("start", "n_11", ""),
                ("start", "n_14", ""),
                ("start", "n_8", ""),
                ("start", "n_10", ""),
                ("start", "n_7", ""),
                ("n_6", "end", ""),
                ("n_5", "end", ""),
                ("n_9", "end", ""),
                ("n_8", "end", ""),
                ("n_10", "end", ""),
                ("n_7", "end", ""),
                ("n_1", "end", ""),
                ("n_14", "end", ""),
                ("n_13", "end", ""),
            ],
        ),
        RuleGraph(
            name="CallExpr",
            nodes={
                "start": NodeLegacy(
                    type=NodeTypeLegacy.START,
                    str_="CallExpr",
                    nonterminal=None,
                    terminal=None,
                    nextNodes=[],
                ),
                "end": NodeLegacy(
                    type=NodeTypeLegacy.END,
                    str_="",
                    nonterminal=None,
                    terminal=None,
                    nextNodes=[],
                ),
                "n_1": NodeLegacy(
                    type=NodeTypeLegacy.TERMINAL,
                    str_="ident",
                    nonterminal=None,
                    terminal="ident",
                    nextNodes=[],
                ),
                "n_2": NodeLegacy(
                    type=NodeTypeLegacy.KEY,
                    str_="(",
                    nonterminal=None,
                    terminal=None,
                    nextNodes=[],
                ),
                "n_3": NodeLegacy(
                    type=NodeTypeLegacy.NONTERMINAL,
                    str_="ArgumentList",
                    nonterminal="ArgumentList",
                    terminal=None,
                    nextNodes=[],
                ),
                "n_4": NodeLegacy(
                    type=NodeTypeLegacy.KEY,
                    str_=")",
                    nonterminal=None,
                    terminal=None,
                    nextNodes=[],
                ),
            },
            edges=[
                ("n_1", "n_2", ""),
                ("n_2", "n_3", ""),
                ("n_3", "n_4", ""),
                ("n_2", "n_4", ""),
                ("start", "n_1", ""),
                ("n_4", "end", ""),
            ],
        ),
        RuleGraph(
            name="CollectionLiteral",
            nodes={
                "start": NodeLegacy(
                    type=NodeTypeLegacy.START,
                    str_="CollectionLiteral",
                    nonterminal=None,
                    terminal=None,
                    nextNodes=[],
                ),
                "end": NodeLegacy(
                    type=NodeTypeLegacy.END,
                    str_="",
                    nonterminal=None,
                    terminal=None,
                    nextNodes=[],
                ),
                "n_1": NodeLegacy(
                    type=NodeTypeLegacy.KEY,
                    str_="[",
                    nonterminal=None,
                    terminal=None,
                    nextNodes=[],
                ),
                "n_2": NodeLegacy(
                    type=NodeTypeLegacy.NONTERMINAL,
                    str_="ArgumentList",
                    nonterminal="ArgumentList",
                    terminal=None,
                    nextNodes=[],
                ),
                "n_3": NodeLegacy(
                    type=NodeTypeLegacy.KEY,
                    str_="]",
                    nonterminal=None,
                    terminal=None,
                    nextNodes=[],
                ),
                "n_4": NodeLegacy(
                    type=NodeTypeLegacy.KEY,
                    str_="{",
                    nonterminal=None,
                    terminal=None,
                    nextNodes=[],
                ),
                "n_5": NodeLegacy(
                    type=NodeTypeLegacy.NONTERMINAL,
                    str_="ArgumentList",
                    nonterminal="ArgumentList",
                    terminal=None,
                    nextNodes=[],
                ),
                "n_6": NodeLegacy(
                    type=NodeTypeLegacy.KEY,
                    str_="}",
                    nonterminal=None,
                    terminal=None,
                    nextNodes=[],
                ),
            },
            edges=[
                ("n_1", "n_2", ""),
                ("n_1", "n_3", ""),
                ("n_2", "n_3", ""),
                ("n_4", "n_5", ""),
                ("n_5", "n_6", ""),
                ("n_4", "n_6", ""),
                ("start", "n_1", ""),
                ("start", "n_4", ""),
                ("n_6", "end", ""),
                ("n_3", "end", ""),
            ],
        ),
        RuleGraph(
            name="ArgumentList",
            nodes={
                "start": NodeLegacy(
                    type=NodeTypeLegacy.START,
                    str_="ArgumentList",
                    nonterminal=None,
                    terminal=None,
                    nextNodes=[],
                ),
                "end": NodeLegacy(
                    type=NodeTypeLegacy.END,
                    str_="",
                    nonterminal=None,
                    terminal=None,
                    nextNodes=[],
                ),
                "n_1": NodeLegacy(
                    type=NodeTypeLegacy.NONTERMINAL,
                    str_="Expression",
                    nonterminal="Expression",
                    terminal=None,
                    nextNodes=[],
                ),
                "n_2": NodeLegacy(
                    type=NodeTypeLegacy.KEY,
                    str_=",",
                    nonterminal=None,
                    terminal=None,
                    nextNodes=[],
                ),
            },
            edges=[
                ("n_1", "n_2", ""),
                ("n_2", "n_1", ""),
                ("start", "n_1", ""),
                ("n_1", "end", ""),
                ("start", "end", ""),
            ],
        ),
        RuleGraph(
            name="ExperimentBlock",
            nodes={
                "start": NodeLegacy(
                    type=NodeTypeLegacy.START,
                    str_="ExperimentBlock",
                    nonterminal=None,
                    terminal=None,
                    nextNodes=[],
                ),
                "end": NodeLegacy(
                    type=NodeTypeLegacy.END,
                    str_="",
                    nonterminal=None,
                    terminal=None,
                    nextNodes=[],
                ),
                "n_1": NodeLegacy(
                    type=NodeTypeLegacy.KEY,
                    str_="EXPERIMENT",
                    nonterminal=None,
                    terminal=None,
                    nextNodes=[],
                ),
                "n_2": NodeLegacy(
                    type=NodeTypeLegacy.TERMINAL,
                    str_="ident",
                    nonterminal=None,
                    terminal="ident",
                    nextNodes=[],
                ),
                "n_3": NodeLegacy(
                    type=NodeTypeLegacy.NONTERMINAL,
                    str_="ExpCommandList",
                    nonterminal="ExpCommandList",
                    terminal=None,
                    nextNodes=[],
                ),
                "n_4": NodeLegacy(
                    type=NodeTypeLegacy.KEY,
                    str_="END",
                    nonterminal=None,
                    terminal=None,
                    nextNodes=[],
                ),
            },
            edges=[
                ("n_1", "n_2", ""),
                ("n_2", "n_3", ""),
                ("n_3", "n_4", ""),
                ("start", "n_1", ""),
                ("n_4", "end", ""),
            ],
        ),
        RuleGraph(
            name="ExpCommandList",
            nodes={
                "start": NodeLegacy(
                    type=NodeTypeLegacy.START,
                    str_="ExpCommandList",
                    nonterminal=None,
                    terminal=None,
                    nextNodes=[],
                ),
                "end": NodeLegacy(
                    type=NodeTypeLegacy.END,
                    str_="",
                    nonterminal=None,
                    terminal=None,
                    nextNodes=[],
                ),
                "n_1": NodeLegacy(
                    type=NodeTypeLegacy.NONTERMINAL,
                    str_="ExpCommand",
                    nonterminal="ExpCommand",
                    terminal=None,
                    nextNodes=[],
                ),
            },
            edges=[
                ("n_1", "n_1", ""),
                ("start", "n_1", ""),
                ("n_1", "end", ""),
                ("start", "end", ""),
            ],
        ),
        RuleGraph(
            name="ExpCommand",
            nodes={
                "start": NodeLegacy(
                    type=NodeTypeLegacy.START,
                    str_="ExpCommand",
                    nonterminal=None,
                    terminal=None,
                    nextNodes=[],
                ),
                "end": NodeLegacy(
                    type=NodeTypeLegacy.END,
                    str_="",
                    nonterminal=None,
                    terminal=None,
                    nextNodes=[],
                ),
                "n_1": NodeLegacy(
                    type=NodeTypeLegacy.NONTERMINAL,
                    str_="ParamCmd",
                    nonterminal="ParamCmd",
                    terminal=None,
                    nextNodes=[],
                ),
                "n_2": NodeLegacy(
                    type=NodeTypeLegacy.NONTERMINAL,
                    str_="TrialsCmd",
                    nonterminal="TrialsCmd",
                    terminal=None,
                    nextNodes=[],
                ),
                "n_3": NodeLegacy(
                    type=NodeTypeLegacy.NONTERMINAL,
                    str_="SeedCmd",
                    nonterminal="SeedCmd",
                    terminal=None,
                    nextNodes=[],
                ),
                "n_4": NodeLegacy(
                    type=NodeTypeLegacy.NONTERMINAL,
                    str_="GenCmd",
                    nonterminal="GenCmd",
                    terminal=None,
                    nextNodes=[],
                ),
                "n_5": NodeLegacy(
                    type=NodeTypeLegacy.NONTERMINAL,
                    str_="CounterCmd",
                    nonterminal="CounterCmd",
                    terminal=None,
                    nextNodes=[],
                ),
                "n_6": NodeLegacy(
                    type=NodeTypeLegacy.NONTERMINAL,
                    str_="StopIfCmd",
                    nonterminal="StopIfCmd",
                    terminal=None,
                    nextNodes=[],
                ),
                "n_7": NodeLegacy(
                    type=NodeTypeLegacy.NONTERMINAL,
                    str_="RunCmd",
                    nonterminal="RunCmd",
                    terminal=None,
                    nextNodes=[],
                ),
                "n_8": NodeLegacy(
                    type=NodeTypeLegacy.NONTERMINAL,
                    str_="ExportCmd",
                    nonterminal="ExportCmd",
                    terminal=None,
                    nextNodes=[],
                ),
            },
            edges=[
                ("start", "n_6", ""),
                ("start", "n_5", ""),
                ("start", "n_8", ""),
                ("start", "n_1", ""),
                ("start", "n_2", ""),
                ("start", "n_3", ""),
                ("start", "n_4", ""),
                ("start", "n_7", ""),
                ("n_6", "end", ""),
                ("n_5", "end", ""),
                ("n_8", "end", ""),
                ("n_1", "end", ""),
                ("n_2", "end", ""),
                ("n_3", "end", ""),
                ("n_4", "end", ""),
                ("n_7", "end", ""),
            ],
        ),
        RuleGraph(
            name="ParamCmd",
            nodes={
                "start": NodeLegacy(
                    type=NodeTypeLegacy.START,
                    str_="ParamCmd",
                    nonterminal=None,
                    terminal=None,
                    nextNodes=[],
                ),
                "end": NodeLegacy(
                    type=NodeTypeLegacy.END,
                    str_="",
                    nonterminal=None,
                    terminal=None,
                    nextNodes=[],
                ),
                "n_1": NodeLegacy(
                    type=NodeTypeLegacy.KEY,
                    str_="PARAM",
                    nonterminal=None,
                    terminal=None,
                    nextNodes=[],
                ),
                "n_2": NodeLegacy(
                    type=NodeTypeLegacy.TERMINAL,
                    str_="ident",
                    nonterminal=None,
                    terminal="ident",
                    nextNodes=[],
                ),
                "n_3": NodeLegacy(
                    type=NodeTypeLegacy.KEY,
                    str_="=",
                    nonterminal=None,
                    terminal=None,
                    nextNodes=[],
                ),
                "n_4": NodeLegacy(
                    type=NodeTypeLegacy.KEY,
                    str_="RANGE",
                    nonterminal=None,
                    terminal=None,
                    nextNodes=[],
                ),
                "n_5": NodeLegacy(
                    type=NodeTypeLegacy.KEY,
                    str_="(",
                    nonterminal=None,
                    terminal=None,
                    nextNodes=[],
                ),
                "n_6": NodeLegacy(
                    type=NodeTypeLegacy.NONTERMINAL,
                    str_="Expression",
                    nonterminal="Expression",
                    terminal=None,
                    nextNodes=[],
                ),
                "n_7": NodeLegacy(
                    type=NodeTypeLegacy.KEY,
                    str_=",",
                    nonterminal=None,
                    terminal=None,
                    nextNodes=[],
                ),
                "n_8": NodeLegacy(
                    type=NodeTypeLegacy.NONTERMINAL,
                    str_="Expression",
                    nonterminal="Expression",
                    terminal=None,
                    nextNodes=[],
                ),
                "n_9": NodeLegacy(
                    type=NodeTypeLegacy.KEY,
                    str_=",",
                    nonterminal=None,
                    terminal=None,
                    nextNodes=[],
                ),
                "n_10": NodeLegacy(
                    type=NodeTypeLegacy.NONTERMINAL,
                    str_="Expression",
                    nonterminal="Expression",
                    terminal=None,
                    nextNodes=[],
                ),
                "n_11": NodeLegacy(
                    type=NodeTypeLegacy.KEY,
                    str_=")",
                    nonterminal=None,
                    terminal=None,
                    nextNodes=[],
                ),
            },
            edges=[
                ("n_1", "n_2", ""),
                ("n_2", "n_3", ""),
                ("n_3", "n_4", ""),
                ("n_4", "n_5", ""),
                ("n_5", "n_6", ""),
                ("n_6", "n_7", ""),
                ("n_7", "n_8", ""),
                ("n_8", "n_9", ""),
                ("n_9", "n_10", ""),
                ("n_10", "n_11", ""),
                ("start", "n_1", ""),
                ("n_11", "end", ""),
            ],
        ),
        RuleGraph(
            name="TrialsCmd",
            nodes={
                "start": NodeLegacy(
                    type=NodeTypeLegacy.START,
                    str_="TrialsCmd",
                    nonterminal=None,
                    terminal=None,
                    nextNodes=[],
                ),
                "end": NodeLegacy(
                    type=NodeTypeLegacy.END,
                    str_="",
                    nonterminal=None,
                    terminal=None,
                    nextNodes=[],
                ),
                "n_1": NodeLegacy(
                    type=NodeTypeLegacy.KEY,
                    str_="TRIALS",
                    nonterminal=None,
                    terminal=None,
                    nextNodes=[],
                ),
                "n_2": NodeLegacy(
                    type=NodeTypeLegacy.TERMINAL,
                    str_="number",
                    nonterminal=None,
                    terminal="number",
                    nextNodes=[],
                ),
            },
            edges=[("n_1", "n_2", ""), ("start", "n_1", ""), ("n_2", "end", "")],
        ),
        RuleGraph(
            name="SeedCmd",
            nodes={
                "start": NodeLegacy(
                    type=NodeTypeLegacy.START,
                    str_="SeedCmd",
                    nonterminal=None,
                    terminal=None,
                    nextNodes=[],
                ),
                "end": NodeLegacy(
                    type=NodeTypeLegacy.END,
                    str_="",
                    nonterminal=None,
                    terminal=None,
                    nextNodes=[],
                ),
                "n_1": NodeLegacy(
                    type=NodeTypeLegacy.KEY,
                    str_="SEED",
                    nonterminal=None,
                    terminal=None,
                    nextNodes=[],
                ),
                "n_2": NodeLegacy(
                    type=NodeTypeLegacy.TERMINAL,
                    str_="number",
                    nonterminal=None,
                    terminal="number",
                    nextNodes=[],
                ),
            },
            edges=[("n_1", "n_2", ""), ("start", "n_1", ""), ("n_2", "end", "")],
        ),
        RuleGraph(
            name="GenCmd",
            nodes={
                "start": NodeLegacy(
                    type=NodeTypeLegacy.START,
                    str_="GenCmd",
                    nonterminal=None,
                    terminal=None,
                    nextNodes=[],
                ),
                "end": NodeLegacy(
                    type=NodeTypeLegacy.END,
                    str_="",
                    nonterminal=None,
                    terminal=None,
                    nextNodes=[],
                ),
                "n_1": NodeLegacy(
                    type=NodeTypeLegacy.KEY,
                    str_="GENERATOR",
                    nonterminal=None,
                    terminal=None,
                    nextNodes=[],
                ),
                "n_2": NodeLegacy(
                    type=NodeTypeLegacy.TERMINAL,
                    str_="ident",
                    nonterminal=None,
                    terminal="ident",
                    nextNodes=[],
                ),
                "n_3": NodeLegacy(
                    type=NodeTypeLegacy.KEY,
                    str_="=",
                    nonterminal=None,
                    terminal=None,
                    nextNodes=[],
                ),
                "n_4": NodeLegacy(
                    type=NodeTypeLegacy.NONTERMINAL,
                    str_="CallExpr",
                    nonterminal="CallExpr",
                    terminal=None,
                    nextNodes=[],
                ),
            },
            edges=[
                ("n_1", "n_2", ""),
                ("n_2", "n_3", ""),
                ("n_3", "n_4", ""),
                ("start", "n_1", ""),
                ("n_4", "end", ""),
            ],
        ),
        RuleGraph(
            name="CounterCmd",
            nodes={
                "start": NodeLegacy(
                    type=NodeTypeLegacy.START,
                    str_="CounterCmd",
                    nonterminal=None,
                    terminal=None,
                    nextNodes=[],
                ),
                "end": NodeLegacy(
                    type=NodeTypeLegacy.END,
                    str_="",
                    nonterminal=None,
                    terminal=None,
                    nextNodes=[],
                ),
                "n_1": NodeLegacy(
                    type=NodeTypeLegacy.KEY,
                    str_="COUNTER",
                    nonterminal=None,
                    terminal=None,
                    nextNodes=[],
                ),
                "n_2": NodeLegacy(
                    type=NodeTypeLegacy.TERMINAL,
                    str_="ident",
                    nonterminal=None,
                    terminal="ident",
                    nextNodes=[],
                ),
                "n_3": NodeLegacy(
                    type=NodeTypeLegacy.KEY,
                    str_="ON",
                    nonterminal=None,
                    terminal=None,
                    nextNodes=[],
                ),
                "n_4": NodeLegacy(
                    type=NodeTypeLegacy.TERMINAL,
                    str_="ident",
                    nonterminal=None,
                    terminal="ident",
                    nextNodes=[],
                ),
                "n_5": NodeLegacy(
                    type=NodeTypeLegacy.KEY,
                    str_="ANY",
                    nonterminal=None,
                    terminal=None,
                    nextNodes=[],
                ),
            },
            edges=[
                ("n_1", "n_2", ""),
                ("n_2", "n_3", ""),
                ("n_3", "n_5", ""),
                ("n_3", "n_4", ""),
                ("start", "n_1", ""),
                ("n_5", "end", ""),
                ("n_4", "end", ""),
            ],
        ),
        RuleGraph(
            name="StopIfCmd",
            nodes={
                "start": NodeLegacy(
                    type=NodeTypeLegacy.START,
                    str_="StopIfCmd",
                    nonterminal=None,
                    terminal=None,
                    nextNodes=[],
                ),
                "end": NodeLegacy(
                    type=NodeTypeLegacy.END,
                    str_="",
                    nonterminal=None,
                    terminal=None,
                    nextNodes=[],
                ),
                "n_1": NodeLegacy(
                    type=NodeTypeLegacy.KEY,
                    str_="STOP_IF",
                    nonterminal=None,
                    terminal=None,
                    nextNodes=[],
                ),
                "n_2": NodeLegacy(
                    type=NodeTypeLegacy.NONTERMINAL,
                    str_="Condition",
                    nonterminal="Condition",
                    terminal=None,
                    nextNodes=[],
                ),
            },
            edges=[("n_1", "n_2", ""), ("start", "n_1", ""), ("n_2", "end", "")],
        ),
        RuleGraph(
            name="RunCmd",
            nodes={
                "start": NodeLegacy(
                    type=NodeTypeLegacy.START,
                    str_="RunCmd",
                    nonterminal=None,
                    terminal=None,
                    nextNodes=[],
                ),
                "end": NodeLegacy(
                    type=NodeTypeLegacy.END,
                    str_="",
                    nonterminal=None,
                    terminal=None,
                    nextNodes=[],
                ),
                "n_1": NodeLegacy(
                    type=NodeTypeLegacy.KEY,
                    str_="RUN",
                    nonterminal=None,
                    terminal=None,
                    nextNodes=[],
                ),
                "n_2": NodeLegacy(
                    type=NodeTypeLegacy.NONTERMINAL,
                    str_="CallExpr",
                    nonterminal="CallExpr",
                    terminal=None,
                    nextNodes=[],
                ),
            },
            edges=[("n_1", "n_2", ""), ("start", "n_1", ""), ("n_2", "end", "")],
        ),
        RuleGraph(
            name="ExportCmd",
            nodes={
                "start": NodeLegacy(
                    type=NodeTypeLegacy.START,
                    str_="ExportCmd",
                    nonterminal=None,
                    terminal=None,
                    nextNodes=[],
                ),
                "end": NodeLegacy(
                    type=NodeTypeLegacy.END,
                    str_="",
                    nonterminal=None,
                    terminal=None,
                    nextNodes=[],
                ),
                "n_1": NodeLegacy(
                    type=NodeTypeLegacy.KEY,
                    str_="EXPORT",
                    nonterminal=None,
                    terminal=None,
                    nextNodes=[],
                ),
                "n_2": NodeLegacy(
                    type=NodeTypeLegacy.TERMINAL,
                    str_="ident",
                    nonterminal=None,
                    terminal="ident",
                    nextNodes=[],
                ),
                "n_3": NodeLegacy(
                    type=NodeTypeLegacy.TERMINAL,
                    str_="string",
                    nonterminal=None,
                    terminal="string",
                    nextNodes=[],
                ),
            },
            edges=[
                ("n_1", "n_2", ""),
                ("n_2", "n_3", ""),
                ("start", "n_1", ""),
                ("n_3", "end", ""),
            ],
        ),
    ],
)
